abstract type AbstractGRASP <: AbstractParameters end

struct GRASP{I, T, L} <: AbstractGRASP
	initial::I
	constructor::T
	local_search::L
end

Base.@kwdef struct GreedyRandomizedContructor
    candidates
    instance = nothing
    α::Float64 = 0.6
    rng = default_rng_mh()
end


function construct(constructor)
    @error "Define your own randomized greedy constructor"
    status.stop = true
    nothing
end

function local_search(x, localsearch, problem)
    @error "Define your own local search"
    nothing
end


function compute_cost(candidates, constructor, instance)
    @warn "Define compute_cost for\nconstructor=$constructor\ninstance=$instance"
    zeros(length(candidates))
end


function construct(constructor::GreedyRandomizedContructor)
    candidates = constructor.candidates |> copy
    α = constructor.α
    # create empty solution S
    S = empty(candidates)
    # construct solution
    while !isempty(candidates)
        cost = compute_cost(candidates, constructor, constructor.instance)
        cmin = minimum(cost)
        cmax = maximum(cost)
        # compute restricted candidate list
        RCL = [i for i in eachindex(candidates) if cost[i] <= cmin + α*(cmax - cmin) ]
        if isempty(RCL)
            @error "RCL is empty. Try increasing α or check your `compute_cost` method."
            return
        end
        
        # select candidate at random and insert into solution
        s = rand(constructor.rng, RCL)
        push!(S, candidates[s])
        # update list of candidates
        deleteat!(candidates, s)
    end
    S
end

function GRASP(;initial=nothing, constructor=nothing, local_search=nothing,
                options = Options(), information=Information())
	# TODO
	if isnothing(constructor) || isnothing(local_search)
        error("Provide a constructor and a local search")
	end
    grasp = GRASP(initial, constructor, local_search)
    Algorithm(grasp; options, information)
end

iscompatible(::BitArraySpace, ::AbstractGRASP) = true
iscompatible(::PermutationSpace, ::AbstractGRASP) = true

function initialize!(status, parameters::AbstractGRASP, problem, information, options, args...; kargs...)

    if isnothing(parameters.initial)
        x0 = rand(options.rng, problem.search_space)
    else
        x0 = parameters.initial
    end
    # set default budget
    options.f_calls_limit = Inf
    if options.iterations <= 0
        options.iterations = 500
    end
    
    sol = create_solution(x0, problem)
	State(sol, [sol])
end

function update_state!(
        status,
        parameters::AbstractGRASP,
        problem,
        information,
        options,
        args...;
        kargs...
    )
    # heuristic construction
    x = construct(parameters.constructor)
    if isnothing(x) || isempty(x)
        status.stop = true
        options.debug && @error """
        Constructor is returning empty solutions. Early stopping optimization.
        """
        return
    elseif options.debug
        @info "Solution generated by `constructor`:\n$x\nPerforming local search..."
    end
    
    # perform local search and evaluate solutions
    x_improved = local_search(x, parameters.local_search, problem)

    # since local search can return a solution without evaluation
    # it is necessary to evaluate objective function
    if x_improved isa AbstractVector
        # evaluate solution
        sol = create_solution(x_improved, problem)
    elseif x_improved isa AbstractSolution
        sol = x_improved
    else
        # seems that local search returned something different to a vector
        return
    end
    options.debug && @info "Local search returned:\n$(get_position(sol))"
    
    # save best solutions
    if is_better(sol, status.best_sol)
        status.best_sol = sol
        options.debug && @info "A better solution was found."
    end
end

function final_stage!(
        status,
        parameters::AbstractGRASP,
        problem,
        information,
        options,
        args...;
        kargs...
   )
   # TODO
   nothing
end

